export const Envs = {
  BUCKET_API: process.env.BUCKET_API,
  BUCKET_API_SECRET_KEY: process.env.BUCKET_API_SECRET_KEY,
  BUCKET_API_KEY: process.env.BUCKET_API_KEY,
  BUCKET_UPLOAD_PRESET: process.env.BUCKET_UPLOAD_PRESET,
}
